# -*- coding: utf-8 -*-
"""24-09-04-hello-world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u7lFhYwuKG_0I_C3Z3pUM0d2tkDeq9v7
"""

print("Hello World!!")

print("Hello Python")

print("Hello Google")

import pylab as by

x_deg = by.arange(-180, 180+1)
x_rad = by.deg2rad(x_deg)
y = by.sin(x_rad)

by.plot(x_deg, y)

by.xlabel('x (deg)')
by.ylabel('sin(x)')
by.grid(True)

